In [343]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn import linear_model
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import preprocessing    

In [344]:
#import data set
data = load_boston()

In [345]:
boston_data = pd.DataFrame(data.data)


In [346]:
boston_data.describe() # no missing values

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [347]:
boston_data.columns = data.feature_names
boston_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [348]:
boston_data['price'] = data.target
boston_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [349]:
reg = linear_model.LinearRegression()
features = [col for col in boston_data.columns if not col == 'price' ]
features

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

In [350]:
reg.fit(boston_data[features],boston_data.price)

LinearRegression()

In [351]:
reg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [352]:
reg.intercept_

36.45948838508978

In [353]:
# get r^2 score for the model
r2_score(boston_data.price,reg.predict(boston_data[features]))

0.7406426641094095

In [354]:
# Get a summary of the model using OLS from statsmodels
X = boston_data[features]
y = boston_data['price'].to_numpy()
X = sm.add_constant(X).to_numpy()
model = sm.OLS(y,X)
results=model.fit()


/home/shimaa/.local/lib/python3.8/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [355]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Wed, 25 Aug 2021   Prob (F-statistic):          6.72e-135
Time:                        09:19:41   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.000      26.432      46.487
x1            -0.1080      0.033     -3.287      0.001      -0.173      -0.043
x2             0.0464      0.014      3.382      0.001       0.019       0.073
x3             0.0206      0.061      0.334      0.738      -0.100       0.141
x4             2.6867      0.862      3.118      0.002       0.994       4.380
x5           -17.7666      3.820     -4.651      0.000     -25.272     -10.262
x6             3.8099      0.418      9.116      0.000       2.989       4.631
x7             0.0007      0.013      0.052      0.958      -0.025       0.027
x8            -1.4756      0.199     -7.398      0.000      -1.867      -1.084
x9             0.3060      0.066      4.613      0.000       0.176       0.436
x10           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
x11           -0.9527      0.131     -7.283      0.000      -1.210      -0.696
x12            0.0093      0.003      3.467      0.001       0.004       0.015
x13           -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## personal class representing multiple linear regression


In [356]:
class MultipleLinearRegression:
    def __init__(self,X,y):
        self.X = X
        self.y = y
        self.n = np.size(self.y)
        self.beta = self.normalEq()
        self.y_mean = (sum(y)/self.n)*np.ones(np.shape(self.y))
        
    def normalEq (self):
        return (np.linalg.inv(self.X.T@self.X)@self.X.T@self.y)
    def getbeta (self):
        return self.beta
    def predict (self,X,b):
        return X@self.beta
    def getSSR (self,b):
        return (self.predict(self.X,b)-self.y_mean).T@(self.predict(self.X,b)-self.y_mean)
    def getSST (self):
        return (self.y-self.y_mean).T@(self.y-self.y_mean)
    def getRSquared (self,b):
        return self.getSSR(b)/self.getSST()
   

In [357]:
my_model = MultipleLinearRegression(X,y)

In [358]:
my_model.getbeta()

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224640e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

In [359]:
my_model.getRSquared(my_model.beta)


0.7406426641093754

## gradient descent function

In [396]:
def gradient_descent(X,y,learning_rate=0.05,num_iter = 1000):
    std_scaler = preprocessing.StandardScaler()
    X = X.to_numpy()
    X = std_scaler.fit_transform(X)
    X = sm.X = sm.add_constant(X)
    (n,p) = np.shape(X)
    beta = np.random.uniform(-10.0, 10.0, p)
    
    
    for i in range (num_iter):
         errors = np.subtract(X.dot(beta),y)
         subt = (learning_rate/n)*(X.T.dot(errors))
         beta -= subt
         #print(beta) 
         #print(cost(X,y,beta))
    return beta    

In [397]:
estimated_beta=gradient_descent(boston_data[features],y)
estimated_beta

array([ 2.25328063e+01, -9.04082329e-01,  1.03934342e+00,  1.08834779e-02,
        7.00312871e-01, -2.03232104e+00,  2.69812553e+00, -6.56399352e-04,
       -3.11211993e+00,  2.33406179e+00, -1.70443741e+00, -2.04812212e+00,
        8.47040534e-01, -3.73105542e+00])

In [ ]:
n = np.size(y)
y_mean = (sum(y)/n)*np.ones(np.shape(y))
def predict (X,beta):
        return X@beta
def getSSR (X,y,beta):
        return (predict(X,beta)-y_mean).T@(predict(X,beta)-y_mean)
def getSST (X,y,beta):
        return (y-y_mean).T@(y-y_mean)
def getRSquared (X,y,beta):
        return getSSR(X,y,beta)/getSST(X,y,beta)

In [ ]:
getRSquared(X,y,estimated_beta)

In [367]:
def cost(X, Y, beta):
  return ((Y - (X @ beta))**2).mean()

## standralization of X and calc R^2 using beta estimated from gradient descent

In [393]:
std_scaler = preprocessing.StandardScaler()
X = boston_data[features].to_numpy()
X = std_scaler.fit_transform(X)
X = sm.X = sm.add_constant(X)
getRSquared(X,y,estimated_beta)

0.739112227122903